### ISSUE TITLE
Not clearing screen effects.

### ISSUE THREAD

**Issue by Cursedth** [Stereowalker/Survive#217]
Tried using temperature since I had it in Though as Nails, but both are a little to much.
However after disabling Survive's temp system the red oval overheat effect remained after reload and wasn't looking to go away since my temp was frozen at 38+Celsius.

Had to turn it back on, cool down for the screen effect to disappear and then turn it off and reload.

regards,

**Comment by Stereowalker** [comment]
Lemme guess, 1.16.5 and using EnhancedVisuals?

**Comment by Cursedth** [comment]
Almost.
1.18.1 and EnhancedVisuals.
Thanks.

**Comment by FreezePhoenix** [comment]
1.18.1 for EnhancedVisuals is no longer receiving updates. Please use 1.18.2.

**Comment by Stereowalker** [comment]
@Cursedth Nothing can be done about it on my end. If I reset the temperature when temperature is disabled, then it will be abused

**Comment by Stereowalker** [comment]
@FreezePhoenix I see that you have an EnhancedVisuals fork. Can you change what is being read for temperature from `temperatureLevel` to `displayTemperature` and make a pull request? -1 is the coldest value and 1 is the hottest value and will always stay that way regardless of how the player modifies the temperature system.

**Comment by FreezePhoenix** [comment]
I don't maintain EnhancedVisuals - but I have notified the maintainer of this solution. Thank you!

**Comment by FreezePhoenix** [comment]
@Cursedth Can you share your configuration for Survive?

**Comment by Stereowalker** [comment]
@FreezePhoenix It's not really a configuration issue. EnhancedVisuals is reading the temperature of the player which doesn't reset when the module is disabled and EnhancedVisuals doesn't take that into account. I'm going to set `displayTemperature` to `0` when the module is disabled so that any feature that checks the player temperature will simply assume the player is warm without needing to check if the module is active or not. Unfortunately for @Cursedth, this will not be a change coming in 1.18.1

**Comment by Stereowalker** [comment]
Also thanks for informing the maintainer

**Comment by FreezePhoenix** [comment]
@Stereowalker How can we query your mod to see if the temperature system is enabled?
I don't think you should have to reset the display temperature to zero, we should just be able to check if the system is enabled.

**Comment by Stereowalker** [comment]
@FreezePhoenix I'm not really resetting the temperature value to 0. `temperatureLevel` will still retain its value regardless of whether or not the module is enabled. `displayTemperature` is calculated from the `temperatureLevel` and scales on the maximum and minimum temperature range of the player giving you a `-1` to `1` value, setting that to `0` will not affect the player as that value is only intended for rendering purposes. You could always check if the module is enabled, but the overlay doesn't really take into account times when the heat and cold resistance attributes are raised higher or lower than `2.0` thus why I recommend using the  `displayTemperature` value so that no further calculation is needed on EnhancedVisuals part

**Comment by Stereowalker** [comment]
If you still insist on checking if it is enabled, use `Survive.TEMPERATURE_CONFIG.enabled`

**Comment by CreativeMD** [comment]
In order to use `displayTemperature` all configurations have to be reset. I also think that the temperature dependent configuration is a little more intuitive. So I guess an is enabled check is more convenient.

**Comment by Stereowalker** [comment]
Oh, okay. Then it looks like I can close this issue. I feel kinda bad for @Cursedth, but neither Survive nor EnhancedVisuals are updating on 1.18.1.

**Comment by CreativeMD** [comment]
@Stereowalker thanks for your help! I hope updating to 1.18.2 shouldn't take too long.

EDIT
@Cursedth you can disable the temperature effect in enhancedvisuals as well. Just use the command /cmdclientconfig.

**Comment by Cursedth** [comment]
Hey folks.
Looks like I started an avalanche of posts.
The bug wasn't that bad or persistent.
Simply disabling and reloading fixes it.
So you really don't have to feel bad for me.
It's mods. They have bugs and compatibility issues all the time
What I knew when I started adding mods :)

I had actually moved to 1.18.2 yesterday :)
I was waiting for a mod to update.

Thanks for all the effort - -d
