### ISSUE TITLE
Stomachache is never ending and unclear in how it functions

### ISSUE THREAD

**Issue by DatVegan** [Stereowalker/Survive#249]
The stomachache effect cannot be cleared and is continuing in my survival world. I have no idea what can cure it. There is no direct config to disable it or do anything about it. Even enabling cheats and clearing effects doesn't work as it instantly brings itself back. There is also no clear reason for why it happened in the first place. Is it due to overeating/drinking? From drinking uncleaned water? Certain foods? And is it supposed to reset itself eventually or continue ticking up over time? Is this tied to the well being mechanic? A lot of questions with no clear answers.

**Comment by DatVegan** [comment]
I may have understood the issue: it's caused by overeating, which when combining this mod with a difficulty mod like Iguanatweaks which reduces the saturation of food and gives hunger after waking up, is technically always. Tweaking when stomach ache occurs (and clearly relaying to the player why it occurs) is advised.

**Comment by Lonemind** [comment]
I'd like to confirm this issue. Documentation for Stomachache would be appreciated.

For DatVegan's benefit I'll share what I've learned. It does seem to be caused by overeating/drinking and I think it is somehow tied with saturation. I also use IguanaTweaks and it's sleep/hunger mechanic. I suspect this somehow messes up Survive's tracking.

Using an install with only Survive installed seems to work a little better. Stomachache seems to vanish when all Saturation is used up with healing. This doesn't fit well when natural healing is turned off or with mods that change that.

Stereowalker, would it be possible to get a config option to turn Stomachache or the overeating feature off?

**Comment by Stereowalker** [comment]
My apologies for the vaguness of the feature and my lack of a timely response to this issue. As per your request, the stomachache feature has been documented into the Survival Guide which can be found in the creative tab provided by this mod in 7.1.2 with the Patchouli mod installed.

The stomachache feature can sort of be turned off in the Server configuration files under the name "Expanded Stomach Capacity". This does not however remove any extra food you happen to gain before turning it off but it will prevent you from filling it past 20.

Although I've added a clear description of how the feature works in the guide, I'll give the details of how it works here. 
1) Your hunger can go past 20 to 40
2) Every 4 points above 20 will raise the amplifier of the Stomach ache debuff by 1
3) Reaching 40 hunger points will deal damage but not kill you
4) You can avoid getting the debuff when you eat food past 20 points if half of the number of points you gain is less than the extra points you gain above 20. An example would be if you eat Steak when you have 16 points of hunger, since that restores 8 points, you won't get the debuff. You will get the debuff if your hunger while eating Steak is more than 16
5) The only way to remove the debuff is to reduce your hunger by consuming large amounts of stamina. Because stamina regenerates from your hunger, using up your stamina reserves will reduce your hunger
6) A new feature to 7.1.2 grants you a Well Fed buff if you happen to get exactly 20 points of hunger from eating
