### ISSUE TITLE
Food Incompability with TerrafirmaCraft Mod

### ISSUE THREAD

**Issue by Shorepion** [Stereowalker/Survive#253]
## 1) Mods
TerraFirmaCraft-Forge-1.18.2-2.1.2-beta
Patchouli-1.18.2-71.1
Survive-1.18.2-7.1.1
UnionLib-1.18.2-7.2.0-Forge

MC 1.18.2

Forge 40.1.74
 
## 2) Crashlog
https://pastebin.com/1myA1NkV
 
## 3) Detailed description of the issue
Crashing to desktop when trying to eat (right clicking) any food.

## 4) Is the issue repeatable?
 Yes

**Comment by alcatrazEscapee** [comment]
This was reported at https://github.com/TerraFirmaCraft/TerraFirmaCraft/issues/2060 as well, so I'll just copy my analysis here:

Survive and TFC both replace the player food stats. However survive does so much more unsafely, because it does not check if their replacement was successful, and blindly casts to it, no `instanceof` check i.e. here

https://github.com/Stereowalker/Survive/blob/c78806ad714bead5879c2be7ec17c7d126d0a560/src/main/java/com/stereowalker/survive/mixins/PlayerMixin.java#L87

And also does not store or retain the original food data and delegate to them where possible, i.e. here:

https://github.com/Stereowalker/Survive/blob/c78806ad714bead5879c2be7ec17c7d126d0a560/src/main/java/com/stereowalker/survive/mixins/PlayerMixin.java#L49

At the end of the day these two mods are likely just an incompatible feature set, however Survive need not hard crash here when present with TFC.

**Comment by Stereowalker** [comment]
I've applied a check to confirm whether the modification was successful and should prevent hard crashes with other mods that do the same thing. But as @alcatrazEscapee pointed out, both mods are likely incompatible unless you specifically want to use specific features from both mods that do not conflict with each other. Thanks for raising this and allowing me to fix it before 1.19
