### ISSUE TITLE
We need option to stack the bottles , also be able to fill it from other tanks

### ISSUE THREAD

**Issue by IVEN2022** [Stereowalker/Survive#256]
Hello
We need option to stack the bottles , also be able to fill it from other tanks that have your fluid , like create tank and immersive eng.

**Comment by Stereowalker** [comment]
Hello, I really hope you read this despite it being 14 days. As for the 2 problems you raised in this issue. 
1) I won't be adding an option to stack bottles, it's what canteens are designed to bypass
2) The reason why this reply took 14 days, I've been working on a small mod UnionLib (Potions & Fluids) and this mod should be able to solve the tank problem. As for what it does, it allows mods to tell each other what potions map to what fluids. However, in order to make this mod useful, the authors of Create and Immersive Engineering both have to use the events provided by this mod to allow myself and various mod authors interested in this feature to tell each other what potions correspond to what fluids.

**Comment by Stereowalker** [comment]
I tried discussing the issue with the author of Immersive Engineering, but they don't seem interested in integrating the API with their mod
