### ISSUE TITLE
Is it possible to disable Stomachache?

### ISSUE THREAD

**Issue by coynereex** [Stereowalker/Survive#259]
I dislike this effect because when you want heal, you eat food and get this effect. If you eat a lot, you can die by Stomachache V. Is it possible to do it?

**Comment by KristoffShiro** [comment]
> I dislike this effect because when you want heal, you eat food and get this effect. If you eat a lot, you can die by Stomachache V. Is it possible to do it?

Yes @coynereex, in the survive-server.toml there is a section at the bottom that says:
`
    [Hunger and Thirst]

    #

    ############################################

    #Should the player be allowed to eat or drink beyond the maximum capacity

    #-------------------------------------------

    #Default: true

    #-------------------------------------------

    "Boolean: Expanded Stomach Capacity" = true

`
change the "Boolean: Expanded Stomach Capacity" to false. This mod actually increases the maximum capacity to 40, but keeps the vanilla capacity of 20 as the soft limit. Disabling the expanded stomach capacity will keep it locked to 20, so you won't get stomachaches anymore (I believe you also won't get the well fed buff either).

**Comment by coynereex** [comment]
I dont know why, but this effect dont disappear. I changed the "Boolean: Expanded Stomach Capacity" to false, but I am still having this effect. :(

**Comment by Stereowalker** [comment]
You won't lose the effect even if you disable it. What that config option does is disables the mechanic that allows you to eat after you have 20 food, you're going to have to work the extra food out of your system to get rid of the stomach ache. You honestly shouldn't be eating past the limits of the game. The point of the feature is to allow the player to sneak in emergency healing even if they're full. The only reason why you're getting a stomach ache is because you're have more than 20 food
