### ISSUE TITLE
Water Canteen does nothing

### ISSUE THREAD

**Issue by BastardNeko** [Stereowalker/Survive#295]
Running 9.0.1 version of the mod on MC 1.20.1, forge 47.1.1. Drinking from canteen, purified or otherwise, restores no thirst meter. Only shift+right clicking to drink water source blocks seems to work. Please help.

**Comment by MissSweetViolet** [comment]
This is happening for me as well, 9.0.1 of survive, 1.20.1 and forge 47.1.0. Drinking from the canteen doesn't effect thirst, and once filled says "no effect" on it

**Comment by BastardNeko** [comment]
Honestly, the mod feels abandoned. I switched to Homeostatic by wendall911 on Curseforge. It's a lot newer, and I find the water bar drain is much more manageable. It's canteen also works. ;P

**Comment by MissSweetViolet** [comment]
It was just updated a few weeks ago, plus we don't know what the mod maker has going on in addition to the mod in real life, I would hardly call it abandoned. I happen to love this mod, and I'm sure the issues will be fixed when there's time.

**Comment by Stereowalker** [comment]
Thank you for reporting the issue, it really helps when I hop back into modding because I can see where there are faults and can fix them before the next release. I've resolved this issue in 9.0.2, but as a side effect, any items, modded or vanilla, that can be consumed and are recognized as a potion in the game will get their data from potions instead.
