### ISSUE TITLE
Purified water in canteen

### ISSUE THREAD

**Issue by FildaGarden** [Stereowalker/Survive#8]
There should be a way to drink purified water from a canteen

**Comment by Stereowalker** [comment]
There isn't one now, but there will be a way soon

**Comment by The-Arcanian** [comment]
@Stereowalker It has been 5 months, what is the status of this? As it stands the canteen is kind of useless.

**Comment by Stereowalker** [comment]
There already is a way to collect purified water in canteens.

**Comment by The-Arcanian** [comment]
How? JEI is no help, and I tried everything I could think of: crafting a canteen with purified bottles, smelting a filled canteen, putting water in a cauldron over a heat source to purify it. And none of the release notes since this issue mention it.

Ohh. Charcoal filters, I did not think of that before... Opening an issue for this because there is nothing to indicate it to the players.
